[package]
name = "day2_cube_conundrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
custom_error = "1.9.2"
miette = "5.10.0"
nom = "7.1.3"
